# Theming
include ~/.local/state/quickshell/user/generated/terminal/kitty-theme.conf

# Font
font_family      AurulentSansMono
font_size 11.0


# Cursor
cursor_shape beam
cursor_trail 1
cursor                #7ec7ff
cursor_text_color     #0b1d2a

#Look
background_opacity 0.35
background            #0f1115
foreground            #cfe8ff
selection_background  #27465c
selection_foreground  #ffffff

color0  #0F1115
color1  #F4ACB6
color2  #C1E4B7
color3  #F1DFBE
color4  #ADC5F7
color5  #F6D0EC
color6  #B1E0D9
color7  #F8C2A8
color8  #A6B3C7
color9  #F6B7C0
color10 #C9E7C1
color11 #F2E3C7
color12 #B8CDF8
color13 #F7D6EF
color14 #BCE4DE
color15 #F9CAB4

# Padding (why weird value? consistency with foot)
window_margin_width 21.75

# No stupid close confirmation
confirm_os_window_close 0

# Use zsh shell
shell zsh

# Copy
map ctrl+c    copy_or_interrupt
map ctrl+v    paste_from_clipboard

# Search
map ctrl+f   launch --location=hsplit --allow-remote-control kitty +kitten search.py @active-kitty-window-id
map kitty_mod+f   launch --location=hsplit --allow-remote-control kitty +kitten search.py @active-kitty-window-id

# Scroll & Zoom
map page_up    scroll_page_up
map page_down    scroll_page_down

map ctrl+plus  change_font_size all +1
map ctrl+equal  change_font_size all +1
map ctrl+kp_add  change_font_size all +1
map ctrl+minus       change_font_size all -1
map ctrl+underscore       change_font_size all -1
map ctrl+kp_subtract       change_font_size all -1
map ctrl+0 change_font_size all 0
map ctrl+kp_0 change_font_size all 0

#Misc
enable_wayland_keyboard yes
map_alt_keys yes
hide_mouse_when_typing yes
